spring:
  datasource:
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 3
      max-wait: 5000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 100
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/edu_test
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver   # 3.2.0开始支持SPI可省略此配置
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/shengshi
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
#        slave_2:
#          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
#          username: ENC(xxxxx)
#          password: ENC(xxxxx)
#          driver-class-name: com.mysql.jdbc.Driver
#          schema: db/schema.sql # 配置则生效,自动初始化表结构
#          data: db/data.sql # 配置则生效,自动初始化数据
#          continue-on-error: true # 默认true,初始化失败是否继续
#          separator: ";" # sql默认分号分隔符


#mybatis plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true        #true是自动把entity变成驼峰式命名，false是数据库里什么样，entity就得什么样
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl       #配置日志

#端口
server:
  port: 8081